on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: niphr/cstemplate/.github/workflows/r-package.yml@a067008fc9b9e97a33b5670d6c6c61ec4464d8d7
