on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: niphr/cstemplate/.github/workflows/r-package.yml@d973c76e09934457f7044c01fc687ad7ea3f19cf
