on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: niphr/cstemplate/.github/workflows/r-package.yml@643ab0c6a9b11dd46b570891e3799096e653e7b9
